---
name: Check Renovate Config
"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed.outputs.all_changed_files }}
      any_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - name: Check for JSON changes
        id: changed
        uses: >-
          tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: |
            mintMaker/**/*.json
          matrix: true
  validate:
    needs: changes
    if: needs.changes.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      - uses: >-
          konflux-ci/renovate-config-validator-action@adca50c2ce7ba1f3fab4d15f8783ad239f8090ae
        with:
          config_file: ${{ matrix.config }}
